ALTER TABLE users
  ADD COLUMN IF NOT EXISTS transfer_alias VARCHAR(100),
  ADD COLUMN IF NOT EXISTS transfer_holder VARCHAR(150),
  ADD COLUMN IF NOT EXISTS transfer_cuit VARCHAR(20),
  ADD COLUMN IF NOT EXISTS transfer_bank VARCHAR(100);
